create table if not exists public.activity_events (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    event_type text not null check (char_length(event_type) between 1 and 64),
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

alter table public.activity_events enable row level security;

create policy "Users can read their own activity"
    on public.activity_events for select
    using (auth.uid() = user_id);

create policy "Users can create their own activity"
    on public.activity_events for insert
    with check (auth.uid() = user_id);

create index if not exists activity_events_user_created_idx
    on public.activity_events (user_id, created_at desc);
